//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./SPARQLParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BigO.SPARQLParser.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SPARQLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface ISPARQLParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.queryUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQueryUnit([NotNull] SPARQLParser.QueryUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.queryUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQueryUnit([NotNull] SPARQLParser.QueryUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.updateUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdateUnit([NotNull] SPARQLParser.UpdateUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.updateUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdateUnit([NotNull] SPARQLParser.UpdateUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] SPARQLParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] SPARQLParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.prologue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrologue([NotNull] SPARQLParser.PrologueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.prologue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrologue([NotNull] SPARQLParser.PrologueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.baseDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseDecl([NotNull] SPARQLParser.BaseDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.baseDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseDecl([NotNull] SPARQLParser.BaseDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.prefixDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixDecl([NotNull] SPARQLParser.PrefixDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.prefixDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixDecl([NotNull] SPARQLParser.PrefixDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.selectQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectQuery([NotNull] SPARQLParser.SelectQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.selectQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectQuery([NotNull] SPARQLParser.SelectQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.subSelect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubSelect([NotNull] SPARQLParser.SubSelectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.subSelect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubSelect([NotNull] SPARQLParser.SubSelectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectClause([NotNull] SPARQLParser.SelectClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectClause([NotNull] SPARQLParser.SelectClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constructQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructQuery([NotNull] SPARQLParser.ConstructQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constructQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructQuery([NotNull] SPARQLParser.ConstructQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.describeQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescribeQuery([NotNull] SPARQLParser.DescribeQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.describeQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescribeQuery([NotNull] SPARQLParser.DescribeQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.askQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAskQuery([NotNull] SPARQLParser.AskQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.askQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAskQuery([NotNull] SPARQLParser.AskQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetClause([NotNull] SPARQLParser.DatasetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetClause([NotNull] SPARQLParser.DatasetClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.defaultGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultGraphClause([NotNull] SPARQLParser.DefaultGraphClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.defaultGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultGraphClause([NotNull] SPARQLParser.DefaultGraphClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.namedGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedGraphClause([NotNull] SPARQLParser.NamedGraphClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.namedGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedGraphClause([NotNull] SPARQLParser.NamedGraphClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSourceSelector([NotNull] SPARQLParser.SourceSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSourceSelector([NotNull] SPARQLParser.SourceSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhereClause([NotNull] SPARQLParser.WhereClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhereClause([NotNull] SPARQLParser.WhereClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.solutionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSolutionModifier([NotNull] SPARQLParser.SolutionModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.solutionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSolutionModifier([NotNull] SPARQLParser.SolutionModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupClause([NotNull] SPARQLParser.GroupClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupClause([NotNull] SPARQLParser.GroupClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupCondition([NotNull] SPARQLParser.GroupConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupCondition([NotNull] SPARQLParser.GroupConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHavingClause([NotNull] SPARQLParser.HavingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHavingClause([NotNull] SPARQLParser.HavingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.havingCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHavingCondition([NotNull] SPARQLParser.HavingConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.havingCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHavingCondition([NotNull] SPARQLParser.HavingConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderClause([NotNull] SPARQLParser.OrderClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderClause([NotNull] SPARQLParser.OrderClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.orderCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderCondition([NotNull] SPARQLParser.OrderConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.orderCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderCondition([NotNull] SPARQLParser.OrderConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.limitOffsetClauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimitOffsetClauses([NotNull] SPARQLParser.LimitOffsetClausesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.limitOffsetClauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimitOffsetClauses([NotNull] SPARQLParser.LimitOffsetClausesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.limitClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimitClause([NotNull] SPARQLParser.LimitClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.limitClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimitClause([NotNull] SPARQLParser.LimitClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.offsetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOffsetClause([NotNull] SPARQLParser.OffsetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.offsetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOffsetClause([NotNull] SPARQLParser.OffsetClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.valuesClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValuesClause([NotNull] SPARQLParser.ValuesClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.valuesClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValuesClause([NotNull] SPARQLParser.ValuesClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.update"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate([NotNull] SPARQLParser.UpdateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.update"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate([NotNull] SPARQLParser.UpdateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.update1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate1([NotNull] SPARQLParser.Update1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.update1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate1([NotNull] SPARQLParser.Update1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.load"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoad([NotNull] SPARQLParser.LoadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.load"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoad([NotNull] SPARQLParser.LoadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.clear"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClear([NotNull] SPARQLParser.ClearContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.clear"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClear([NotNull] SPARQLParser.ClearContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop([NotNull] SPARQLParser.DropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop([NotNull] SPARQLParser.DropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.create"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate([NotNull] SPARQLParser.CreateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.create"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate([NotNull] SPARQLParser.CreateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd([NotNull] SPARQLParser.AddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd([NotNull] SPARQLParser.AddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMove([NotNull] SPARQLParser.MoveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMove([NotNull] SPARQLParser.MoveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.copy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCopy([NotNull] SPARQLParser.CopyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.copy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCopy([NotNull] SPARQLParser.CopyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.insertData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsertData([NotNull] SPARQLParser.InsertDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.insertData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsertData([NotNull] SPARQLParser.InsertDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.deleteData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteData([NotNull] SPARQLParser.DeleteDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.deleteData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteData([NotNull] SPARQLParser.DeleteDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.deleteWhere"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteWhere([NotNull] SPARQLParser.DeleteWhereContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.deleteWhere"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteWhere([NotNull] SPARQLParser.DeleteWhereContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.modify"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModify([NotNull] SPARQLParser.ModifyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.modify"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModify([NotNull] SPARQLParser.ModifyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.deleteClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteClause([NotNull] SPARQLParser.DeleteClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.deleteClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteClause([NotNull] SPARQLParser.DeleteClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.insertClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsertClause([NotNull] SPARQLParser.InsertClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.insertClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsertClause([NotNull] SPARQLParser.InsertClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.usingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingClause([NotNull] SPARQLParser.UsingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.usingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingClause([NotNull] SPARQLParser.UsingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphOrDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphOrDefault([NotNull] SPARQLParser.GraphOrDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphOrDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphOrDefault([NotNull] SPARQLParser.GraphOrDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphRef([NotNull] SPARQLParser.GraphRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphRef([NotNull] SPARQLParser.GraphRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphRefAll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphRefAll([NotNull] SPARQLParser.GraphRefAllContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphRefAll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphRefAll([NotNull] SPARQLParser.GraphRefAllContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quadPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuadPattern([NotNull] SPARQLParser.QuadPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quadPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuadPattern([NotNull] SPARQLParser.QuadPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quadData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuadData([NotNull] SPARQLParser.QuadDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quadData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuadData([NotNull] SPARQLParser.QuadDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quads"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuads([NotNull] SPARQLParser.QuadsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quads"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuads([NotNull] SPARQLParser.QuadsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quadsNotTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuadsNotTriples([NotNull] SPARQLParser.QuadsNotTriplesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quadsNotTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuadsNotTriples([NotNull] SPARQLParser.QuadsNotTriplesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesTemplate([NotNull] SPARQLParser.TriplesTemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesTemplate([NotNull] SPARQLParser.TriplesTemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupGraphPattern([NotNull] SPARQLParser.GroupGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupGraphPattern([NotNull] SPARQLParser.GroupGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupGraphPatternSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupGraphPatternSub([NotNull] SPARQLParser.GroupGraphPatternSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupGraphPatternSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupGraphPatternSub([NotNull] SPARQLParser.GroupGraphPatternSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesBlock([NotNull] SPARQLParser.TriplesBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesBlock([NotNull] SPARQLParser.TriplesBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphPatternNotTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphPatternNotTriples([NotNull] SPARQLParser.GraphPatternNotTriplesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphPatternNotTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphPatternNotTriples([NotNull] SPARQLParser.GraphPatternNotTriplesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.optionalGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalGraphPattern([NotNull] SPARQLParser.OptionalGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.optionalGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalGraphPattern([NotNull] SPARQLParser.OptionalGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphGraphPattern([NotNull] SPARQLParser.GraphGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphGraphPattern([NotNull] SPARQLParser.GraphGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.serviceGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterServiceGraphPattern([NotNull] SPARQLParser.ServiceGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.serviceGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitServiceGraphPattern([NotNull] SPARQLParser.ServiceGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.bind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBind([NotNull] SPARQLParser.BindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.bind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBind([NotNull] SPARQLParser.BindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.inlineData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineData([NotNull] SPARQLParser.InlineDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.inlineData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineData([NotNull] SPARQLParser.InlineDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.dataBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataBlock([NotNull] SPARQLParser.DataBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.dataBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataBlock([NotNull] SPARQLParser.DataBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.inlineDataOneVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineDataOneVar([NotNull] SPARQLParser.InlineDataOneVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.inlineDataOneVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineDataOneVar([NotNull] SPARQLParser.InlineDataOneVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.inlineDataFull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineDataFull([NotNull] SPARQLParser.InlineDataFullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.inlineDataFull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineDataFull([NotNull] SPARQLParser.InlineDataFullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.dataBlockValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataBlockValue([NotNull] SPARQLParser.DataBlockValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.dataBlockValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataBlockValue([NotNull] SPARQLParser.DataBlockValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.minusGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinusGraphPattern([NotNull] SPARQLParser.MinusGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.minusGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinusGraphPattern([NotNull] SPARQLParser.MinusGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupOrUnionGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupOrUnionGraphPattern([NotNull] SPARQLParser.GroupOrUnionGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupOrUnionGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupOrUnionGraphPattern([NotNull] SPARQLParser.GroupOrUnionGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter([NotNull] SPARQLParser.FilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter([NotNull] SPARQLParser.FilterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] SPARQLParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] SPARQLParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] SPARQLParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] SPARQLParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] SPARQLParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] SPARQLParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] SPARQLParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] SPARQLParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constructTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructTemplate([NotNull] SPARQLParser.ConstructTemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constructTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructTemplate([NotNull] SPARQLParser.ConstructTemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constructTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructTriples([NotNull] SPARQLParser.ConstructTriplesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constructTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructTriples([NotNull] SPARQLParser.ConstructTriplesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesSameSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesSameSubject([NotNull] SPARQLParser.TriplesSameSubjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesSameSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesSameSubject([NotNull] SPARQLParser.TriplesSameSubjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyList([NotNull] SPARQLParser.PropertyListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyList([NotNull] SPARQLParser.PropertyListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyListNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyListNotEmpty([NotNull] SPARQLParser.PropertyListNotEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyListNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyListNotEmpty([NotNull] SPARQLParser.PropertyListNotEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.verb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVerb([NotNull] SPARQLParser.VerbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.verb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVerb([NotNull] SPARQLParser.VerbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectList([NotNull] SPARQLParser.ObjectListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectList([NotNull] SPARQLParser.ObjectListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] SPARQLParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] SPARQLParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesSameSubjectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesSameSubjectPath([NotNull] SPARQLParser.TriplesSameSubjectPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesSameSubjectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesSameSubjectPath([NotNull] SPARQLParser.TriplesSameSubjectPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyListPath([NotNull] SPARQLParser.PropertyListPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyListPath([NotNull] SPARQLParser.PropertyListPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyListPathNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyListPathNotEmpty([NotNull] SPARQLParser.PropertyListPathNotEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyListPathNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyListPathNotEmpty([NotNull] SPARQLParser.PropertyListPathNotEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.verbPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVerbPath([NotNull] SPARQLParser.VerbPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.verbPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVerbPath([NotNull] SPARQLParser.VerbPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.verbSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVerbSimple([NotNull] SPARQLParser.VerbSimpleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.verbSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVerbSimple([NotNull] SPARQLParser.VerbSimpleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.objectListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectListPath([NotNull] SPARQLParser.ObjectListPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.objectListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectListPath([NotNull] SPARQLParser.ObjectListPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.objectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectPath([NotNull] SPARQLParser.ObjectPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.objectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectPath([NotNull] SPARQLParser.ObjectPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] SPARQLParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] SPARQLParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathAlternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathAlternative([NotNull] SPARQLParser.PathAlternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathAlternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathAlternative([NotNull] SPARQLParser.PathAlternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathSequence([NotNull] SPARQLParser.PathSequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathSequence([NotNull] SPARQLParser.PathSequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathElt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathElt([NotNull] SPARQLParser.PathEltContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathElt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathElt([NotNull] SPARQLParser.PathEltContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathEltOrInverse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathEltOrInverse([NotNull] SPARQLParser.PathEltOrInverseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathEltOrInverse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathEltOrInverse([NotNull] SPARQLParser.PathEltOrInverseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathMod([NotNull] SPARQLParser.PathModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathMod([NotNull] SPARQLParser.PathModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathPrimary([NotNull] SPARQLParser.PathPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathPrimary([NotNull] SPARQLParser.PathPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathNegatedPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathNegatedPropertySet([NotNull] SPARQLParser.PathNegatedPropertySetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathNegatedPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathNegatedPropertySet([NotNull] SPARQLParser.PathNegatedPropertySetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathOneInPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathOneInPropertySet([NotNull] SPARQLParser.PathOneInPropertySetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathOneInPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathOneInPropertySet([NotNull] SPARQLParser.PathOneInPropertySetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesNode([NotNull] SPARQLParser.TriplesNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesNode([NotNull] SPARQLParser.TriplesNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.blankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankNodePropertyList([NotNull] SPARQLParser.BlankNodePropertyListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.blankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankNodePropertyList([NotNull] SPARQLParser.BlankNodePropertyListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesNodePath([NotNull] SPARQLParser.TriplesNodePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesNodePath([NotNull] SPARQLParser.TriplesNodePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.blankNodePropertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankNodePropertyListPath([NotNull] SPARQLParser.BlankNodePropertyListPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.blankNodePropertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankNodePropertyListPath([NotNull] SPARQLParser.BlankNodePropertyListPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollection([NotNull] SPARQLParser.CollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollection([NotNull] SPARQLParser.CollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.collectionPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionPath([NotNull] SPARQLParser.CollectionPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.collectionPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionPath([NotNull] SPARQLParser.CollectionPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphNode([NotNull] SPARQLParser.GraphNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphNode([NotNull] SPARQLParser.GraphNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphNodePath([NotNull] SPARQLParser.GraphNodePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphNodePath([NotNull] SPARQLParser.GraphNodePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.varOrTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrTerm([NotNull] SPARQLParser.VarOrTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.varOrTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrTerm([NotNull] SPARQLParser.VarOrTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.varOrIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrIri([NotNull] SPARQLParser.VarOrIriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.varOrIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrIri([NotNull] SPARQLParser.VarOrIriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] SPARQLParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] SPARQLParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphTerm([NotNull] SPARQLParser.GraphTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphTerm([NotNull] SPARQLParser.GraphTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SPARQLParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SPARQLParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalOrExpression([NotNull] SPARQLParser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalOrExpression([NotNull] SPARQLParser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalAndExpression([NotNull] SPARQLParser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalAndExpression([NotNull] SPARQLParser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.valueLogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueLogical([NotNull] SPARQLParser.ValueLogicalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.valueLogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueLogical([NotNull] SPARQLParser.ValueLogicalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] SPARQLParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] SPARQLParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericExpression([NotNull] SPARQLParser.NumericExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericExpression([NotNull] SPARQLParser.NumericExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] SPARQLParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] SPARQLParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] SPARQLParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] SPARQLParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] SPARQLParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] SPARQLParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] SPARQLParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] SPARQLParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.brackettedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrackettedExpression([NotNull] SPARQLParser.BrackettedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.brackettedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrackettedExpression([NotNull] SPARQLParser.BrackettedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.builtInCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInCall([NotNull] SPARQLParser.BuiltInCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.builtInCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInCall([NotNull] SPARQLParser.BuiltInCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.regexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexExpression([NotNull] SPARQLParser.RegexExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.regexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexExpression([NotNull] SPARQLParser.RegexExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.substringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubstringExpression([NotNull] SPARQLParser.SubstringExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.substringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubstringExpression([NotNull] SPARQLParser.SubstringExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.strReplaceExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrReplaceExpression([NotNull] SPARQLParser.StrReplaceExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.strReplaceExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrReplaceExpression([NotNull] SPARQLParser.StrReplaceExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.existsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExistsFunc([NotNull] SPARQLParser.ExistsFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.existsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExistsFunc([NotNull] SPARQLParser.ExistsFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.notExistsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExistsFunc([NotNull] SPARQLParser.NotExistsFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.notExistsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExistsFunc([NotNull] SPARQLParser.NotExistsFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregate([NotNull] SPARQLParser.AggregateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregate([NotNull] SPARQLParser.AggregateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.iriOrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIriOrFunction([NotNull] SPARQLParser.IriOrFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.iriOrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIriOrFunction([NotNull] SPARQLParser.IriOrFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.rdfLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRdfLiteral([NotNull] SPARQLParser.RdfLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.rdfLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRdfLiteral([NotNull] SPARQLParser.RdfLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteral([NotNull] SPARQLParser.NumericLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteral([NotNull] SPARQLParser.NumericLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteralUnsigned"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteralUnsigned([NotNull] SPARQLParser.NumericLiteralUnsignedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteralUnsigned"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteralUnsigned([NotNull] SPARQLParser.NumericLiteralUnsignedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteralPositive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteralPositive([NotNull] SPARQLParser.NumericLiteralPositiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteralPositive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteralPositive([NotNull] SPARQLParser.NumericLiteralPositiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteralNegative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteralNegative([NotNull] SPARQLParser.NumericLiteralNegativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteralNegative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteralNegative([NotNull] SPARQLParser.NumericLiteralNegativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] SPARQLParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] SPARQLParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] SPARQLParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] SPARQLParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIri([NotNull] SPARQLParser.IriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIri([NotNull] SPARQLParser.IriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.prefixedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixedName([NotNull] SPARQLParser.PrefixedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.prefixedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixedName([NotNull] SPARQLParser.PrefixedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.blankNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankNode([NotNull] SPARQLParser.BlankNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.blankNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankNode([NotNull] SPARQLParser.BlankNodeContext context);
}
} // namespace BigO.SPARQLParser.Parser
