//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./SPARQLParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BigO.SPARQLParser.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISPARQLParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SPARQLParserBaseListener : ISPARQLParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.queryUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQueryUnit([NotNull] SPARQLParser.QueryUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.queryUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQueryUnit([NotNull] SPARQLParser.QueryUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuery([NotNull] SPARQLParser.QueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuery([NotNull] SPARQLParser.QueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.updateUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdateUnit([NotNull] SPARQLParser.UpdateUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.updateUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdateUnit([NotNull] SPARQLParser.UpdateUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.prologue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrologue([NotNull] SPARQLParser.PrologueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.prologue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrologue([NotNull] SPARQLParser.PrologueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.baseDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseDecl([NotNull] SPARQLParser.BaseDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.baseDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseDecl([NotNull] SPARQLParser.BaseDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.prefixDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixDecl([NotNull] SPARQLParser.PrefixDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.prefixDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixDecl([NotNull] SPARQLParser.PrefixDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.selectQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectQuery([NotNull] SPARQLParser.SelectQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.selectQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectQuery([NotNull] SPARQLParser.SelectQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.subSelect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubSelect([NotNull] SPARQLParser.SubSelectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.subSelect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubSelect([NotNull] SPARQLParser.SubSelectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.selectClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectClause([NotNull] SPARQLParser.SelectClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.selectClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectClause([NotNull] SPARQLParser.SelectClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constructQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructQuery([NotNull] SPARQLParser.ConstructQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constructQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructQuery([NotNull] SPARQLParser.ConstructQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.describeQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescribeQuery([NotNull] SPARQLParser.DescribeQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.describeQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescribeQuery([NotNull] SPARQLParser.DescribeQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.askQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAskQuery([NotNull] SPARQLParser.AskQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.askQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAskQuery([NotNull] SPARQLParser.AskQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.datasetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatasetClause([NotNull] SPARQLParser.DatasetClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.datasetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatasetClause([NotNull] SPARQLParser.DatasetClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.defaultGraphClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultGraphClause([NotNull] SPARQLParser.DefaultGraphClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.defaultGraphClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultGraphClause([NotNull] SPARQLParser.DefaultGraphClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.namedGraphClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedGraphClause([NotNull] SPARQLParser.NamedGraphClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.namedGraphClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedGraphClause([NotNull] SPARQLParser.NamedGraphClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.sourceSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSourceSelector([NotNull] SPARQLParser.SourceSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.sourceSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSourceSelector([NotNull] SPARQLParser.SourceSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.whereClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhereClause([NotNull] SPARQLParser.WhereClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.whereClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhereClause([NotNull] SPARQLParser.WhereClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.solutionModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSolutionModifier([NotNull] SPARQLParser.SolutionModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.solutionModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSolutionModifier([NotNull] SPARQLParser.SolutionModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupClause([NotNull] SPARQLParser.GroupClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupClause([NotNull] SPARQLParser.GroupClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupCondition([NotNull] SPARQLParser.GroupConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupCondition([NotNull] SPARQLParser.GroupConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.havingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHavingClause([NotNull] SPARQLParser.HavingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.havingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHavingClause([NotNull] SPARQLParser.HavingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.havingCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHavingCondition([NotNull] SPARQLParser.HavingConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.havingCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHavingCondition([NotNull] SPARQLParser.HavingConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderClause([NotNull] SPARQLParser.OrderClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderClause([NotNull] SPARQLParser.OrderClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.orderCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderCondition([NotNull] SPARQLParser.OrderConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.orderCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderCondition([NotNull] SPARQLParser.OrderConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.limitOffsetClauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimitOffsetClauses([NotNull] SPARQLParser.LimitOffsetClausesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.limitOffsetClauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimitOffsetClauses([NotNull] SPARQLParser.LimitOffsetClausesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.limitClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimitClause([NotNull] SPARQLParser.LimitClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.limitClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimitClause([NotNull] SPARQLParser.LimitClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.offsetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOffsetClause([NotNull] SPARQLParser.OffsetClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.offsetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOffsetClause([NotNull] SPARQLParser.OffsetClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.valuesClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValuesClause([NotNull] SPARQLParser.ValuesClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.valuesClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValuesClause([NotNull] SPARQLParser.ValuesClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.update"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdate([NotNull] SPARQLParser.UpdateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.update"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdate([NotNull] SPARQLParser.UpdateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.update1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdate1([NotNull] SPARQLParser.Update1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.update1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdate1([NotNull] SPARQLParser.Update1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.load"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad([NotNull] SPARQLParser.LoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.load"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad([NotNull] SPARQLParser.LoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.clear"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClear([NotNull] SPARQLParser.ClearContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.clear"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClear([NotNull] SPARQLParser.ClearContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop([NotNull] SPARQLParser.DropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop([NotNull] SPARQLParser.DropContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.create"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate([NotNull] SPARQLParser.CreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.create"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate([NotNull] SPARQLParser.CreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] SPARQLParser.AddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] SPARQLParser.AddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMove([NotNull] SPARQLParser.MoveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.move"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMove([NotNull] SPARQLParser.MoveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.copy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCopy([NotNull] SPARQLParser.CopyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.copy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCopy([NotNull] SPARQLParser.CopyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.insertData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsertData([NotNull] SPARQLParser.InsertDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.insertData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsertData([NotNull] SPARQLParser.InsertDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.deleteData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteData([NotNull] SPARQLParser.DeleteDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.deleteData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteData([NotNull] SPARQLParser.DeleteDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.deleteWhere"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteWhere([NotNull] SPARQLParser.DeleteWhereContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.deleteWhere"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteWhere([NotNull] SPARQLParser.DeleteWhereContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.modify"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModify([NotNull] SPARQLParser.ModifyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.modify"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModify([NotNull] SPARQLParser.ModifyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.deleteClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteClause([NotNull] SPARQLParser.DeleteClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.deleteClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteClause([NotNull] SPARQLParser.DeleteClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.insertClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsertClause([NotNull] SPARQLParser.InsertClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.insertClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsertClause([NotNull] SPARQLParser.InsertClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.usingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingClause([NotNull] SPARQLParser.UsingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.usingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingClause([NotNull] SPARQLParser.UsingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphOrDefault"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphOrDefault([NotNull] SPARQLParser.GraphOrDefaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphOrDefault"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphOrDefault([NotNull] SPARQLParser.GraphOrDefaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphRef([NotNull] SPARQLParser.GraphRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphRef([NotNull] SPARQLParser.GraphRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphRefAll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphRefAll([NotNull] SPARQLParser.GraphRefAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphRefAll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphRefAll([NotNull] SPARQLParser.GraphRefAllContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quadPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuadPattern([NotNull] SPARQLParser.QuadPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quadPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuadPattern([NotNull] SPARQLParser.QuadPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quadData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuadData([NotNull] SPARQLParser.QuadDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quadData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuadData([NotNull] SPARQLParser.QuadDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quads"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuads([NotNull] SPARQLParser.QuadsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quads"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuads([NotNull] SPARQLParser.QuadsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.quadsNotTriples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuadsNotTriples([NotNull] SPARQLParser.QuadsNotTriplesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.quadsNotTriples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuadsNotTriples([NotNull] SPARQLParser.QuadsNotTriplesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesTemplate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplesTemplate([NotNull] SPARQLParser.TriplesTemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesTemplate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplesTemplate([NotNull] SPARQLParser.TriplesTemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupGraphPattern([NotNull] SPARQLParser.GroupGraphPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupGraphPattern([NotNull] SPARQLParser.GroupGraphPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupGraphPatternSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupGraphPatternSub([NotNull] SPARQLParser.GroupGraphPatternSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupGraphPatternSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupGraphPatternSub([NotNull] SPARQLParser.GroupGraphPatternSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplesBlock([NotNull] SPARQLParser.TriplesBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplesBlock([NotNull] SPARQLParser.TriplesBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphPatternNotTriples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphPatternNotTriples([NotNull] SPARQLParser.GraphPatternNotTriplesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphPatternNotTriples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphPatternNotTriples([NotNull] SPARQLParser.GraphPatternNotTriplesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.optionalGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalGraphPattern([NotNull] SPARQLParser.OptionalGraphPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.optionalGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalGraphPattern([NotNull] SPARQLParser.OptionalGraphPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphGraphPattern([NotNull] SPARQLParser.GraphGraphPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphGraphPattern([NotNull] SPARQLParser.GraphGraphPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.serviceGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServiceGraphPattern([NotNull] SPARQLParser.ServiceGraphPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.serviceGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServiceGraphPattern([NotNull] SPARQLParser.ServiceGraphPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.bind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBind([NotNull] SPARQLParser.BindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.bind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBind([NotNull] SPARQLParser.BindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.inlineData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineData([NotNull] SPARQLParser.InlineDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.inlineData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineData([NotNull] SPARQLParser.InlineDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.dataBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataBlock([NotNull] SPARQLParser.DataBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.dataBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataBlock([NotNull] SPARQLParser.DataBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.inlineDataOneVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineDataOneVar([NotNull] SPARQLParser.InlineDataOneVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.inlineDataOneVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineDataOneVar([NotNull] SPARQLParser.InlineDataOneVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.inlineDataFull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineDataFull([NotNull] SPARQLParser.InlineDataFullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.inlineDataFull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineDataFull([NotNull] SPARQLParser.InlineDataFullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.dataBlockValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataBlockValue([NotNull] SPARQLParser.DataBlockValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.dataBlockValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataBlockValue([NotNull] SPARQLParser.DataBlockValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.minusGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinusGraphPattern([NotNull] SPARQLParser.MinusGraphPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.minusGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinusGraphPattern([NotNull] SPARQLParser.MinusGraphPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.groupOrUnionGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupOrUnionGraphPattern([NotNull] SPARQLParser.GroupOrUnionGraphPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.groupOrUnionGraphPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupOrUnionGraphPattern([NotNull] SPARQLParser.GroupOrUnionGraphPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter([NotNull] SPARQLParser.FilterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter([NotNull] SPARQLParser.FilterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstraint([NotNull] SPARQLParser.ConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstraint([NotNull] SPARQLParser.ConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] SPARQLParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] SPARQLParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] SPARQLParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] SPARQLParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] SPARQLParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] SPARQLParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constructTemplate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructTemplate([NotNull] SPARQLParser.ConstructTemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constructTemplate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructTemplate([NotNull] SPARQLParser.ConstructTemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.constructTriples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructTriples([NotNull] SPARQLParser.ConstructTriplesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.constructTriples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructTriples([NotNull] SPARQLParser.ConstructTriplesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesSameSubject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplesSameSubject([NotNull] SPARQLParser.TriplesSameSubjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesSameSubject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplesSameSubject([NotNull] SPARQLParser.TriplesSameSubjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyList([NotNull] SPARQLParser.PropertyListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyList([NotNull] SPARQLParser.PropertyListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyListNotEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyListNotEmpty([NotNull] SPARQLParser.PropertyListNotEmptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyListNotEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyListNotEmpty([NotNull] SPARQLParser.PropertyListNotEmptyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.verb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVerb([NotNull] SPARQLParser.VerbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.verb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVerb([NotNull] SPARQLParser.VerbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.objectList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectList([NotNull] SPARQLParser.ObjectListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.objectList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectList([NotNull] SPARQLParser.ObjectListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] SPARQLParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] SPARQLParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesSameSubjectPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplesSameSubjectPath([NotNull] SPARQLParser.TriplesSameSubjectPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesSameSubjectPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplesSameSubjectPath([NotNull] SPARQLParser.TriplesSameSubjectPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyListPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyListPath([NotNull] SPARQLParser.PropertyListPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyListPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyListPath([NotNull] SPARQLParser.PropertyListPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.propertyListPathNotEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyListPathNotEmpty([NotNull] SPARQLParser.PropertyListPathNotEmptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.propertyListPathNotEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyListPathNotEmpty([NotNull] SPARQLParser.PropertyListPathNotEmptyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.verbPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVerbPath([NotNull] SPARQLParser.VerbPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.verbPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVerbPath([NotNull] SPARQLParser.VerbPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.verbSimple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVerbSimple([NotNull] SPARQLParser.VerbSimpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.verbSimple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVerbSimple([NotNull] SPARQLParser.VerbSimpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.objectListPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectListPath([NotNull] SPARQLParser.ObjectListPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.objectListPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectListPath([NotNull] SPARQLParser.ObjectListPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.objectPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectPath([NotNull] SPARQLParser.ObjectPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.objectPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectPath([NotNull] SPARQLParser.ObjectPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] SPARQLParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] SPARQLParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathAlternative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathAlternative([NotNull] SPARQLParser.PathAlternativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathAlternative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathAlternative([NotNull] SPARQLParser.PathAlternativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathSequence([NotNull] SPARQLParser.PathSequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathSequence([NotNull] SPARQLParser.PathSequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathElt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathElt([NotNull] SPARQLParser.PathEltContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathElt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathElt([NotNull] SPARQLParser.PathEltContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathEltOrInverse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathEltOrInverse([NotNull] SPARQLParser.PathEltOrInverseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathEltOrInverse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathEltOrInverse([NotNull] SPARQLParser.PathEltOrInverseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathMod([NotNull] SPARQLParser.PathModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathMod([NotNull] SPARQLParser.PathModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathPrimary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathPrimary([NotNull] SPARQLParser.PathPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathPrimary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathPrimary([NotNull] SPARQLParser.PathPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathNegatedPropertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathNegatedPropertySet([NotNull] SPARQLParser.PathNegatedPropertySetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathNegatedPropertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathNegatedPropertySet([NotNull] SPARQLParser.PathNegatedPropertySetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.pathOneInPropertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathOneInPropertySet([NotNull] SPARQLParser.PathOneInPropertySetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.pathOneInPropertySet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathOneInPropertySet([NotNull] SPARQLParser.PathOneInPropertySetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplesNode([NotNull] SPARQLParser.TriplesNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplesNode([NotNull] SPARQLParser.TriplesNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.blankNodePropertyList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlankNodePropertyList([NotNull] SPARQLParser.BlankNodePropertyListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.blankNodePropertyList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlankNodePropertyList([NotNull] SPARQLParser.BlankNodePropertyListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.triplesNodePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplesNodePath([NotNull] SPARQLParser.TriplesNodePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.triplesNodePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplesNodePath([NotNull] SPARQLParser.TriplesNodePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.blankNodePropertyListPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlankNodePropertyListPath([NotNull] SPARQLParser.BlankNodePropertyListPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.blankNodePropertyListPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlankNodePropertyListPath([NotNull] SPARQLParser.BlankNodePropertyListPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollection([NotNull] SPARQLParser.CollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollection([NotNull] SPARQLParser.CollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.collectionPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollectionPath([NotNull] SPARQLParser.CollectionPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.collectionPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollectionPath([NotNull] SPARQLParser.CollectionPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphNode([NotNull] SPARQLParser.GraphNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphNode([NotNull] SPARQLParser.GraphNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphNodePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphNodePath([NotNull] SPARQLParser.GraphNodePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphNodePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphNodePath([NotNull] SPARQLParser.GraphNodePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.varOrTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrTerm([NotNull] SPARQLParser.VarOrTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.varOrTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrTerm([NotNull] SPARQLParser.VarOrTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.varOrIri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrIri([NotNull] SPARQLParser.VarOrIriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.varOrIri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrIri([NotNull] SPARQLParser.VarOrIriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] SPARQLParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] SPARQLParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.graphTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphTerm([NotNull] SPARQLParser.GraphTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.graphTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphTerm([NotNull] SPARQLParser.GraphTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] SPARQLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] SPARQLParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.conditionalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalOrExpression([NotNull] SPARQLParser.ConditionalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.conditionalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalOrExpression([NotNull] SPARQLParser.ConditionalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.conditionalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalAndExpression([NotNull] SPARQLParser.ConditionalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.conditionalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalAndExpression([NotNull] SPARQLParser.ConditionalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.valueLogical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueLogical([NotNull] SPARQLParser.ValueLogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.valueLogical"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueLogical([NotNull] SPARQLParser.ValueLogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] SPARQLParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] SPARQLParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericExpression([NotNull] SPARQLParser.NumericExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericExpression([NotNull] SPARQLParser.NumericExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] SPARQLParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] SPARQLParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] SPARQLParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] SPARQLParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] SPARQLParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] SPARQLParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] SPARQLParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] SPARQLParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.brackettedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBrackettedExpression([NotNull] SPARQLParser.BrackettedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.brackettedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBrackettedExpression([NotNull] SPARQLParser.BrackettedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.builtInCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltInCall([NotNull] SPARQLParser.BuiltInCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.builtInCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltInCall([NotNull] SPARQLParser.BuiltInCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.regexExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexExpression([NotNull] SPARQLParser.RegexExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.regexExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexExpression([NotNull] SPARQLParser.RegexExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.substringExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubstringExpression([NotNull] SPARQLParser.SubstringExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.substringExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubstringExpression([NotNull] SPARQLParser.SubstringExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.strReplaceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrReplaceExpression([NotNull] SPARQLParser.StrReplaceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.strReplaceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrReplaceExpression([NotNull] SPARQLParser.StrReplaceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.existsFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExistsFunc([NotNull] SPARQLParser.ExistsFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.existsFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExistsFunc([NotNull] SPARQLParser.ExistsFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.notExistsFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExistsFunc([NotNull] SPARQLParser.NotExistsFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.notExistsFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExistsFunc([NotNull] SPARQLParser.NotExistsFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.aggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregate([NotNull] SPARQLParser.AggregateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.aggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregate([NotNull] SPARQLParser.AggregateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.iriOrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIriOrFunction([NotNull] SPARQLParser.IriOrFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.iriOrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIriOrFunction([NotNull] SPARQLParser.IriOrFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.rdfLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRdfLiteral([NotNull] SPARQLParser.RdfLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.rdfLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRdfLiteral([NotNull] SPARQLParser.RdfLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericLiteral([NotNull] SPARQLParser.NumericLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericLiteral([NotNull] SPARQLParser.NumericLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteralUnsigned"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericLiteralUnsigned([NotNull] SPARQLParser.NumericLiteralUnsignedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteralUnsigned"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericLiteralUnsigned([NotNull] SPARQLParser.NumericLiteralUnsignedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteralPositive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericLiteralPositive([NotNull] SPARQLParser.NumericLiteralPositiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteralPositive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericLiteralPositive([NotNull] SPARQLParser.NumericLiteralPositiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.numericLiteralNegative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericLiteralNegative([NotNull] SPARQLParser.NumericLiteralNegativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.numericLiteralNegative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericLiteralNegative([NotNull] SPARQLParser.NumericLiteralNegativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] SPARQLParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] SPARQLParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] SPARQLParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] SPARQLParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.iri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIri([NotNull] SPARQLParser.IriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.iri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIri([NotNull] SPARQLParser.IriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.prefixedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixedName([NotNull] SPARQLParser.PrefixedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.prefixedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixedName([NotNull] SPARQLParser.PrefixedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SPARQLParser.blankNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlankNode([NotNull] SPARQLParser.BlankNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SPARQLParser.blankNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlankNode([NotNull] SPARQLParser.BlankNodeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace BigO.SPARQLParser.Parser
