name: Release to NuGet

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: cd BigO.SPARQLParser && dotnet build -c Release
    - name: Test
      run: cd BigO.SPARQLParser.Tests && dotnet test -c Release
    - name: Pack nugets
      run: cd BigO.SPARQLParser && dotnet pack -c Release --no-build --output .
    - name: Push to NuGet
      run: cd BigO.SPARQLParser && dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json